# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_main_windowtStUYu.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QGroupBox,
    QHeaderView, QLabel, QLineEdit, QMainWindow,
    QMenuBar, QPushButton, QSizePolicy, QStatusBar,
    QTabWidget, QTableWidget, QTableWidgetItem, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(783, 618)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 791, 441))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.pushButton_start_real_time = QPushButton(self.tab)
        self.pushButton_start_real_time.setObjectName(u"pushButton_start_real_time")
        self.pushButton_start_real_time.setGeometry(QRect(10, 10, 131, 51))
        self.pushButton_2_stop_real_time = QPushButton(self.tab)
        self.pushButton_2_stop_real_time.setObjectName(u"pushButton_2_stop_real_time")
        self.pushButton_2_stop_real_time.setGeometry(QRect(150, 10, 131, 51))
        self.groupBox_2 = QGroupBox(self.tab)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 80, 771, 151))
        self.lineEdit_Params_Values = QLineEdit(self.groupBox_2)
        self.lineEdit_Params_Values.setObjectName(u"lineEdit_Params_Values")
        self.lineEdit_Params_Values.setGeometry(QRect(10, 30, 751, 111))
        font = QFont()
        font.setPointSize(18)
        self.lineEdit_Params_Values.setFont(font)
        self.UserConfirmationButton = QPushButton(self.tab)
        self.UserConfirmationButton.setObjectName(u"UserConfirmationButton")
        self.UserConfirmationButton.setGeometry(QRect(10, 230, 771, 51))
        self.label_Real_Time = QLabel(self.tab)
        self.label_Real_Time.setObjectName(u"label_Real_Time")
        self.label_Real_Time.setGeometry(QRect(290, 20, 31, 31))
        self.label_7 = QLabel(self.tab)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(470, 20, 131, 41))
        font1 = QFont()
        font1.setPointSize(17)
        self.label_7.setFont(font1)
        self.label_8_action_number_label = QLabel(self.tab)
        self.label_8_action_number_label.setObjectName(u"label_8_action_number_label")
        self.label_8_action_number_label.setGeometry(QRect(610, 20, 131, 41))
        self.label_8_action_number_label.setFont(font1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.groupBox = QGroupBox(self.tab_2)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(0, 310, 781, 101))
        self.tableWidget_Params = QTableWidget(self.groupBox)
        if (self.tableWidget_Params.columnCount() < 3):
            self.tableWidget_Params.setColumnCount(3)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget_Params.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget_Params.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget_Params.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        if (self.tableWidget_Params.rowCount() < 1):
            self.tableWidget_Params.setRowCount(1)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget_Params.setItem(0, 0, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget_Params.setItem(0, 1, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableWidget_Params.setItem(0, 2, __qtablewidgetitem5)
        self.tableWidget_Params.setObjectName(u"tableWidget_Params")
        self.tableWidget_Params.setGeometry(QRect(0, 20, 781, 71))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_Params.sizePolicy().hasHeightForWidth())
        self.tableWidget_Params.setSizePolicy(sizePolicy)
        self.tableWidget_Params.setRowCount(1)
        self.tableWidget_Params.setColumnCount(3)
        self.tabWidget_2 = QTabWidget(self.tab_2)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(0, 0, 781, 301))
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.groupBox_4 = QGroupBox(self.tab_5)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(0, 0, 431, 61))
        self.lineEdit_Beep_Duration_Upon_New_Params = QLineEdit(self.groupBox_4)
        self.lineEdit_Beep_Duration_Upon_New_Params.setObjectName(u"lineEdit_Beep_Duration_Upon_New_Params")
        self.lineEdit_Beep_Duration_Upon_New_Params.setGeometry(QRect(290, 20, 141, 22))
        self.label = QLabel(self.groupBox_4)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(210, 20, 71, 16))
        self.comboBo_New_results_Sound = QComboBox(self.groupBox_4)
        self.comboBo_New_results_Sound.addItem("")
        self.comboBo_New_results_Sound.addItem("")
        self.comboBo_New_results_Sound.addItem("")
        self.comboBo_New_results_Sound.setObjectName(u"comboBo_New_results_Sound")
        self.comboBo_New_results_Sound.setGeometry(QRect(10, 20, 181, 22))
        self.groupBox_7 = QGroupBox(self.tab_5)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(0, 60, 431, 101))
        self.checkBox_ProgressCharts = QCheckBox(self.groupBox_7)
        self.checkBox_ProgressCharts.setObjectName(u"checkBox_ProgressCharts")
        self.checkBox_ProgressCharts.setGeometry(QRect(30, 20, 161, 20))
        self.checkBox_ProgressCharts.setChecked(True)
        self.checkBox_Limit_Time_Series_Flag = QCheckBox(self.groupBox_7)
        self.checkBox_Limit_Time_Series_Flag.setObjectName(u"checkBox_Limit_Time_Series_Flag")
        self.checkBox_Limit_Time_Series_Flag.setGeometry(QRect(30, 40, 281, 20))
        self.checkBox_Limit_Time_Series_Flag.setChecked(True)
        self.label_4 = QLabel(self.groupBox_7)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 70, 91, 16))
        self.lineEdit_Series_samples_number = QLineEdit(self.groupBox_7)
        self.lineEdit_Series_samples_number.setObjectName(u"lineEdit_Series_samples_number")
        self.lineEdit_Series_samples_number.setGeometry(QRect(116, 68, 181, 22))
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.groupBox_3 = QGroupBox(self.tab_6)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(0, 0, 561, 141))
        self.comboBox_controlALgorithm = QComboBox(self.groupBox_3)
        self.comboBox_controlALgorithm.addItem("")
        self.comboBox_controlALgorithm.addItem("")
        self.comboBox_controlALgorithm.setObjectName(u"comboBox_controlALgorithm")
        self.comboBox_controlALgorithm.setGeometry(QRect(250, 30, 301, 22))
        self.label_10 = QLabel(self.groupBox_3)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 30, 101, 16))
        self.label_11 = QLabel(self.groupBox_3)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(250, 10, 101, 16))
        self.comboBox_datasource = QComboBox(self.groupBox_3)
        self.comboBox_datasource.addItem("")
        self.comboBox_datasource.addItem("")
        self.comboBox_datasource.addItem("")
        self.comboBox_datasource.setObjectName(u"comboBox_datasource")
        self.comboBox_datasource.setGeometry(QRect(10, 60, 221, 22))
        self.tabWidget_3 = QTabWidget(self.groupBox_3)
        self.tabWidget_3.setObjectName(u"tabWidget_3")
        self.tabWidget_3.setGeometry(QRect(250, 50, 301, 81))
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.label_13 = QLabel(self.tab_3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(1, 3, 71, 16))
        self.lineEdit_Determenistic_time_period_text = QLineEdit(self.tab_3)
        self.lineEdit_Determenistic_time_period_text.setObjectName(u"lineEdit_Determenistic_time_period_text")
        self.lineEdit_Determenistic_time_period_text.setGeometry(QRect(72, 0, 81, 22))
        self.label_14 = QLabel(self.tab_3)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(0, 30, 71, 16))
        self.lineEdit_Determenistic_pointsnum_text = QLineEdit(self.tab_3)
        self.lineEdit_Determenistic_pointsnum_text.setObjectName(u"lineEdit_Determenistic_pointsnum_text")
        self.lineEdit_Determenistic_pointsnum_text.setGeometry(QRect(71, 25, 81, 22))
        self.pushButton = QPushButton(self.tab_3)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(170, 0, 121, 51))
        self.tabWidget_3.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.tabWidget_3.addTab(self.tab_4, "")
        self.groupBox_8 = QGroupBox(self.tab_6)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(0, 140, 561, 51))
        self.comboBox_controlALgorithm_waitingtime_flag = QComboBox(self.groupBox_8)
        self.comboBox_controlALgorithm_waitingtime_flag.addItem("")
        self.comboBox_controlALgorithm_waitingtime_flag.addItem("")
        self.comboBox_controlALgorithm_waitingtime_flag.setObjectName(u"comboBox_controlALgorithm_waitingtime_flag")
        self.comboBox_controlALgorithm_waitingtime_flag.setGeometry(QRect(7, 15, 391, 22))
        self.lineEdit_Beep_Duration_Upon_New_Params_3 = QLineEdit(self.groupBox_8)
        self.lineEdit_Beep_Duration_Upon_New_Params_3.setObjectName(u"lineEdit_Beep_Duration_Upon_New_Params_3")
        self.lineEdit_Beep_Duration_Upon_New_Params_3.setGeometry(QRect(494, 15, 61, 22))
        self.label_2 = QLabel(self.groupBox_8)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(407, 18, 91, 16))
        self.groupBox_9 = QGroupBox(self.tab_6)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(0, 200, 561, 71))
        self.comboBox_controlALgorithm_feedback_confirmation_flag = QComboBox(self.groupBox_9)
        self.comboBox_controlALgorithm_feedback_confirmation_flag.addItem("")
        self.comboBox_controlALgorithm_feedback_confirmation_flag.addItem("")
        self.comboBox_controlALgorithm_feedback_confirmation_flag.setObjectName(u"comboBox_controlALgorithm_feedback_confirmation_flag")
        self.comboBox_controlALgorithm_feedback_confirmation_flag.setGeometry(QRect(10, 40, 161, 22))
        self.label_12 = QLabel(self.groupBox_9)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 20, 111, 16))
        self.checkBox_UValuesRound_flag = QCheckBox(self.groupBox_9)
        self.checkBox_UValuesRound_flag.setObjectName(u"checkBox_UValuesRound_flag")
        self.checkBox_UValuesRound_flag.setGeometry(QRect(190, 40, 111, 20))
        self.checkBox_UValuesRound_flag.setChecked(True)
        self.lineEdit_RoundUValuesNumber = QLineEdit(self.groupBox_9)
        self.lineEdit_RoundUValuesNumber.setObjectName(u"lineEdit_RoundUValuesNumber")
        self.lineEdit_RoundUValuesNumber.setGeometry(QRect(300, 40, 101, 22))
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.groupBox_10 = QGroupBox(self.tab_7)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(0, 0, 601, 111))
        self.lineEdit_Beep_Duration_Upon_New_Params_5 = QLineEdit(self.groupBox_10)
        self.lineEdit_Beep_Duration_Upon_New_Params_5.setObjectName(u"lineEdit_Beep_Duration_Upon_New_Params_5")
        self.lineEdit_Beep_Duration_Upon_New_Params_5.setGeometry(QRect(0, 20, 431, 22))
        self.pushButton_ethalons_load = QPushButton(self.groupBox_10)
        self.pushButton_ethalons_load.setObjectName(u"pushButton_ethalons_load")
        self.pushButton_ethalons_load.setGeometry(QRect(4, 50, 431, 24))
        self.label_5_ethalons_label = QLabel(self.groupBox_10)
        self.label_5_ethalons_label.setObjectName(u"label_5_ethalons_label")
        self.label_5_ethalons_label.setGeometry(QRect(10, 80, 21, 16))
        self.label_5 = QLabel(self.groupBox_10)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(40, 80, 111, 16))
        self.pushButton_ethalons_clear = QPushButton(self.groupBox_10)
        self.pushButton_ethalons_clear.setObjectName(u"pushButton_ethalons_clear")
        self.pushButton_ethalons_clear.setGeometry(QRect(140, 80, 461, 24))
        self.pushButton_ethalons_setFixedValue = QPushButton(self.groupBox_10)
        self.pushButton_ethalons_setFixedValue.setObjectName(u"pushButton_ethalons_setFixedValue")
        self.pushButton_ethalons_setFixedValue.setGeometry(QRect(440, 50, 161, 24))
        self.lineEdit_etalonvalueparameter = QLineEdit(self.groupBox_10)
        self.lineEdit_etalonvalueparameter.setObjectName(u"lineEdit_etalonvalueparameter")
        self.lineEdit_etalonvalueparameter.setGeometry(QRect(440, 20, 161, 22))
        self.groupBox_11 = QGroupBox(self.tab_7)
        self.groupBox_11.setObjectName(u"groupBox_11")
        self.groupBox_11.setGeometry(QRect(0, 201, 431, 101))
        self.lineEdit_Beep_Duration_Upon_New_Params_6 = QLineEdit(self.groupBox_11)
        self.lineEdit_Beep_Duration_Upon_New_Params_6.setObjectName(u"lineEdit_Beep_Duration_Upon_New_Params_6")
        self.lineEdit_Beep_Duration_Upon_New_Params_6.setGeometry(QRect(0, 20, 431, 22))
        self.pushButton_ethalons_vs_other_data_brows = QPushButton(self.groupBox_11)
        self.pushButton_ethalons_vs_other_data_brows.setObjectName(u"pushButton_ethalons_vs_other_data_brows")
        self.pushButton_ethalons_vs_other_data_brows.setGeometry(QRect(4, 43, 421, 24))
        self.pushButton_ethalons_vs_other_data_2 = QPushButton(self.groupBox_11)
        self.pushButton_ethalons_vs_other_data_2.setObjectName(u"pushButton_ethalons_vs_other_data_2")
        self.pushButton_ethalons_vs_other_data_2.setGeometry(QRect(2, 68, 131, 24))
        self.label_3_check_dataload = QLabel(self.groupBox_11)
        self.label_3_check_dataload.setObjectName(u"label_3_check_dataload")
        self.label_3_check_dataload.setGeometry(QRect(140, 73, 281, 16))
        self.groupBox_12 = QGroupBox(self.tab_7)
        self.groupBox_12.setObjectName(u"groupBox_12")
        self.groupBox_12.setGeometry(QRect(0, 110, 431, 91))
        self.comboBox_controlALgorithm_summator_type = QComboBox(self.groupBox_12)
        self.comboBox_controlALgorithm_summator_type.addItem("")
        self.comboBox_controlALgorithm_summator_type.addItem("")
        self.comboBox_controlALgorithm_summator_type.addItem("")
        self.comboBox_controlALgorithm_summator_type.addItem("")
        self.comboBox_controlALgorithm_summator_type.addItem("")
        self.comboBox_controlALgorithm_summator_type.addItem("")
        self.comboBox_controlALgorithm_summator_type.setObjectName(u"comboBox_controlALgorithm_summator_type")
        self.comboBox_controlALgorithm_summator_type.setGeometry(QRect(60, 20, 91, 22))
        self.comboBox_controlALgorithm_summator_err_type_2 = QComboBox(self.groupBox_12)
        self.comboBox_controlALgorithm_summator_err_type_2.addItem("")
        self.comboBox_controlALgorithm_summator_err_type_2.addItem("")
        self.comboBox_controlALgorithm_summator_err_type_2.addItem("")
        self.comboBox_controlALgorithm_summator_err_type_2.addItem("")
        self.comboBox_controlALgorithm_summator_err_type_2.setObjectName(u"comboBox_controlALgorithm_summator_err_type_2")
        self.comboBox_controlALgorithm_summator_err_type_2.setGeometry(QRect(180, 20, 71, 22))
        self.label_3 = QLabel(self.groupBox_12)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(153, 20, 49, 16))
        self.label_6 = QLabel(self.groupBox_12)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 20, 49, 16))
        self.label_8 = QLabel(self.groupBox_12)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(250, 20, 49, 16))
        self.comboBox_controlALgorithm_summator_features_type_3 = QComboBox(self.groupBox_12)
        self.comboBox_controlALgorithm_summator_features_type_3.addItem("")
        self.comboBox_controlALgorithm_summator_features_type_3.addItem("")
        self.comboBox_controlALgorithm_summator_features_type_3.addItem("")
        self.comboBox_controlALgorithm_summator_features_type_3.setObjectName(u"comboBox_controlALgorithm_summator_features_type_3")
        self.comboBox_controlALgorithm_summator_features_type_3.setGeometry(QRect(300, 20, 121, 22))
        self.label_9 = QLabel(self.groupBox_12)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 50, 91, 16))
        self.lineEdit_real_time_folder = QLineEdit(self.groupBox_12)
        self.lineEdit_real_time_folder.setObjectName(u"lineEdit_real_time_folder")
        self.lineEdit_real_time_folder.setGeometry(QRect(7, 66, 341, 22))
        self.pushButton_real_time_folder_browse = QPushButton(self.groupBox_12)
        self.pushButton_real_time_folder_browse.setObjectName(u"pushButton_real_time_folder_browse")
        self.pushButton_real_time_folder_browse.setGeometry(QRect(351, 65, 71, 24))
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_8 = QWidget()
        self.tab_8.setObjectName(u"tab_8")
        self.groupBox_5 = QGroupBox(self.tab_8)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(0, 0, 431, 51))
        self.checkBox_LOG_info_to_console = QCheckBox(self.groupBox_5)
        self.checkBox_LOG_info_to_console.setObjectName(u"checkBox_LOG_info_to_console")
        self.checkBox_LOG_info_to_console.setGeometry(QRect(20, 20, 161, 20))
        self.checkBox_LOG_info_to_console.setChecked(True)
        self.groupBox_6 = QGroupBox(self.tab_8)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(0, 50, 431, 101))
        self.checkBox_LOG_info_file = QCheckBox(self.groupBox_6)
        self.checkBox_LOG_info_file.setObjectName(u"checkBox_LOG_info_file")
        self.checkBox_LOG_info_file.setGeometry(QRect(20, 20, 161, 20))
        self.lineEdit_Beep_Duration_Upon_New_Params_2 = QLineEdit(self.groupBox_6)
        self.lineEdit_Beep_Duration_Upon_New_Params_2.setObjectName(u"lineEdit_Beep_Duration_Upon_New_Params_2")
        self.lineEdit_Beep_Duration_Upon_New_Params_2.setGeometry(QRect(10, 40, 411, 22))
        self.checkBox_LOG_info_file_limit_flag = QCheckBox(self.groupBox_6)
        self.checkBox_LOG_info_file_limit_flag.setObjectName(u"checkBox_LOG_info_file_limit_flag")
        self.checkBox_LOG_info_file_limit_flag.setGeometry(QRect(20, 70, 221, 20))
        self.checkBox_LOG_info_file_limit_flag.setChecked(True)
        self.lineEdit_info_file_limit_value = QLineEdit(self.groupBox_6)
        self.lineEdit_info_file_limit_value.setObjectName(u"lineEdit_info_file_limit_value")
        self.lineEdit_info_file_limit_value.setGeometry(QRect(250, 70, 91, 22))
        self.tabWidget_2.addTab(self.tab_8, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.ExitButton = QPushButton(self.centralwidget)
        self.ExitButton.setObjectName(u"ExitButton")
        self.ExitButton.setGeometry(QRect(700, 530, 81, 41))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 783, 33))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pushButton_start_real_time.setText(QCoreApplication.translate("MainWindow", u"Start real time", None))
        self.pushButton_2_stop_real_time.setText(QCoreApplication.translate("MainWindow", u"Stop real time", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Current parameters values", None))
        self.UserConfirmationButton.setText(QCoreApplication.translate("MainWindow", u"Confirm changes", None))
        self.label_Real_Time.setText("")
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Action num.:", None))
        self.label_8_action_number_label.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Real time", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"List of initial parameters", None))
        ___qtablewidgetitem = self.tableWidget_Params.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Parameter Name", None));
        ___qtablewidgetitem1 = self.tableWidget_Params.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Min value", None));
        ___qtablewidgetitem2 = self.tableWidget_Params.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Max value", None));

        __sortingEnabled = self.tableWidget_Params.isSortingEnabled()
        self.tableWidget_Params.setSortingEnabled(False)
        ___qtablewidgetitem3 = self.tableWidget_Params.item(0, 0)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Pressure", None));
        ___qtablewidgetitem4 = self.tableWidget_Params.item(0, 1)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"20", None));
        ___qtablewidgetitem5 = self.tableWidget_Params.item(0, 2)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"30", None));
        self.tableWidget_Params.setSortingEnabled(__sortingEnabled)

        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Beep when new values are ready", None))
        self.lineEdit_Beep_Duration_Upon_New_Params.setText(QCoreApplication.translate("MainWindow", u"0.25", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Duration(s):", None))
        self.comboBo_New_results_Sound.setItemText(0, QCoreApplication.translate("MainWindow", u"Beep_continious", None))
        self.comboBo_New_results_Sound.setItemText(1, QCoreApplication.translate("MainWindow", u"Beep_alternating", None))
        self.comboBo_New_results_Sound.setItemText(2, QCoreApplication.translate("MainWindow", u"No_beep", None))

        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"File LOG", None))
        self.checkBox_ProgressCharts.setText(QCoreApplication.translate("MainWindow", u"Show charts with progress", None))
        self.checkBox_Limit_Time_Series_Flag.setText(QCoreApplication.translate("MainWindow", u"Limit charts series to a fixed number of samples", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Samples num.:", None))
        self.lineEdit_Series_samples_number.setText(QCoreApplication.translate("MainWindow", u"100", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"Sound/vizualization", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Control algorithm/input data source", None))
        self.comboBox_controlALgorithm.setItemText(0, QCoreApplication.translate("MainWindow", u"Determenistic", None))
        self.comboBox_controlALgorithm.setItemText(1, QCoreApplication.translate("MainWindow", u"Stochastic", None))

        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Input:", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"AntiAction", None))
        self.comboBox_datasource.setItemText(0, QCoreApplication.translate("MainWindow", u"Rand_data", None))
        self.comboBox_datasource.setItemText(1, QCoreApplication.translate("MainWindow", u"Linear_response", None))
        self.comboBox_datasource.setItemText(2, QCoreApplication.translate("MainWindow", u"Real_data", None))

        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Time period:", None))
        self.lineEdit_Determenistic_time_period_text.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Points num.:", None))
        self.lineEdit_Determenistic_pointsnum_text.setText(QCoreApplication.translate("MainWindow", u"10000", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"test", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Determenistic", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"Tab 2", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"Waiting times", None))
        self.comboBox_controlALgorithm_waitingtime_flag.setItemText(0, QCoreApplication.translate("MainWindow", u"No waiting", None))
        self.comboBox_controlALgorithm_waitingtime_flag.setItemText(1, QCoreApplication.translate("MainWindow", u"Waiting after each control action with duration (s):", None))

        self.comboBox_controlALgorithm_waitingtime_flag.setCurrentText(QCoreApplication.translate("MainWindow", u"No waiting", None))
        self.lineEdit_Beep_Duration_Upon_New_Params_3.setText(QCoreApplication.translate("MainWindow", u"1.25", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Waiting time (s):", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("MainWindow", u"Feedback", None))
        self.comboBox_controlALgorithm_feedback_confirmation_flag.setItemText(0, QCoreApplication.translate("MainWindow", u"Operator confirms", None))
        self.comboBox_controlALgorithm_feedback_confirmation_flag.setItemText(1, QCoreApplication.translate("MainWindow", u"Automatic operation", None))

        self.comboBox_controlALgorithm_feedback_confirmation_flag.setCurrentText(QCoreApplication.translate("MainWindow", u"Operator confirms", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Type of feedback:", None))
        self.checkBox_UValuesRound_flag.setText(QCoreApplication.translate("MainWindow", u"Round U values:", None))
        self.lineEdit_RoundUValuesNumber.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), QCoreApplication.translate("MainWindow", u"Control", None))
        self.groupBox_10.setTitle(QCoreApplication.translate("MainWindow", u"Load etalons", None))
        self.lineEdit_Beep_Duration_Upon_New_Params_5.setText(QCoreApplication.translate("MainWindow", u"C:\\Tmp\\KANNAN\\zst2_00214", None))
        self.pushButton_ethalons_load.setText(QCoreApplication.translate("MainWindow", u"Brows folder and load", None))
        self.label_5_ethalons_label.setText("")
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Etalons loaded", None))
        self.pushButton_ethalons_clear.setText(QCoreApplication.translate("MainWindow", u"Clean etalons", None))
        self.pushButton_ethalons_setFixedValue.setText(QCoreApplication.translate("MainWindow", u"Set fixed value", None))
        self.lineEdit_etalonvalueparameter.setText(QCoreApplication.translate("MainWindow", u"32.1", None))
        self.groupBox_11.setTitle(QCoreApplication.translate("MainWindow", u"Check etalons against other data", None))
        self.lineEdit_Beep_Duration_Upon_New_Params_6.setText(QCoreApplication.translate("MainWindow", u"C:\\Tmp\\KANNAN\\zst2_00214", None))
        self.pushButton_ethalons_vs_other_data_brows.setText(QCoreApplication.translate("MainWindow", u"Brows folder and load", None))
        self.pushButton_ethalons_vs_other_data_2.setText(QCoreApplication.translate("MainWindow", u"Check", None))
        self.label_3_check_dataload.setText("")
        self.groupBox_12.setTitle(QCoreApplication.translate("MainWindow", u"Summator", None))
        self.comboBox_controlALgorithm_summator_type.setItemText(0, QCoreApplication.translate("MainWindow", u"Heat_kernel", None))
        self.comboBox_controlALgorithm_summator_type.setItemText(1, QCoreApplication.translate("MainWindow", u"Polin_kernel", None))
        self.comboBox_controlALgorithm_summator_type.setItemText(2, QCoreApplication.translate("MainWindow", u"KME", None))
        self.comboBox_controlALgorithm_summator_type.setItemText(3, QCoreApplication.translate("MainWindow", u"Laplacian_kernel", None))
        self.comboBox_controlALgorithm_summator_type.setItemText(4, QCoreApplication.translate("MainWindow", u"ChiSquare_kernel", None))
        self.comboBox_controlALgorithm_summator_type.setItemText(5, QCoreApplication.translate("MainWindow", u"Subtract", None))

        self.comboBox_controlALgorithm_summator_err_type_2.setItemText(0, QCoreApplication.translate("MainWindow", u"average", None))
        self.comboBox_controlALgorithm_summator_err_type_2.setItemText(1, QCoreApplication.translate("MainWindow", u"min", None))
        self.comboBox_controlALgorithm_summator_err_type_2.setItemText(2, QCoreApplication.translate("MainWindow", u"max", None))
        self.comboBox_controlALgorithm_summator_err_type_2.setItemText(3, QCoreApplication.translate("MainWindow", u"last", None))

        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Error", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Distance", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Features", None))
        self.comboBox_controlALgorithm_summator_features_type_3.setItemText(0, QCoreApplication.translate("MainWindow", u"FFT_spectra", None))
        self.comboBox_controlALgorithm_summator_features_type_3.setItemText(1, QCoreApplication.translate("MainWindow", u"DF_features", None))
        self.comboBox_controlALgorithm_summator_features_type_3.setItemText(2, QCoreApplication.translate("MainWindow", u"JM_frequencies", None))

        self.comboBox_controlALgorithm_summator_features_type_3.setCurrentText(QCoreApplication.translate("MainWindow", u"FFT_spectra", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Real time folder", None))
        self.lineEdit_real_time_folder.setText(QCoreApplication.translate("MainWindow", u"C:\\Tmp\\KANNAN\\zst2_00214", None))
        self.pushButton_real_time_folder_browse.setText(QCoreApplication.translate("MainWindow", u"Browse", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), QCoreApplication.translate("MainWindow", u"Summators/feedback", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"Console LOG", None))
        self.checkBox_LOG_info_to_console.setText(QCoreApplication.translate("MainWindow", u"Print LOG info to console", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"File LOG", None))
        self.checkBox_LOG_info_file.setText(QCoreApplication.translate("MainWindow", u"Keep file LOG", None))
        self.lineEdit_Beep_Duration_Upon_New_Params_2.setText(QCoreApplication.translate("MainWindow", u"c:\\\\tmp\\\\ghjk.csv", None))
        self.checkBox_LOG_info_file_limit_flag.setText(QCoreApplication.translate("MainWindow", u"Limit number of records in each LOG", None))
        self.lineEdit_info_file_limit_value.setText(QCoreApplication.translate("MainWindow", u"1000", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), QCoreApplication.translate("MainWindow", u"LOG", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Settings", None))
        self.ExitButton.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
    # retranslateUi

